// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3GHUyVhui6BwQmhQlW535SeLzoAWyJJg',
    appId: '1:321100725894:web:58578a0a1a4b41e4235b07',
    messagingSenderId: '321100725894',
    projectId: 'cocherasnestle',
    authDomain: 'cocherasnestle.firebaseapp.com',
    storageBucket: 'cocherasnestle.firebasestorage.app',
    measurementId: 'G-E72W9FW2GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDki8w-C8TFlow3BQmEWAKwwORuJL8fLL0',
    appId: '1:321100725894:android:8db97a6e68a68355235b07',
    messagingSenderId: '321100725894',
    projectId: 'cocherasnestle',
    storageBucket: 'cocherasnestle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp_J1xa2DUeIFfni8-jEoCtR-wS-JeRiw',
    appId: '1:321100725894:ios:b01087e9c9ecea88235b07',
    messagingSenderId: '321100725894',
    projectId: 'cocherasnestle',
    storageBucket: 'cocherasnestle.firebasestorage.app',
    androidClientId: '321100725894-i3l5nua49f92i5e0lvtu7qiju01krv0t.apps.googleusercontent.com',
    iosClientId: '321100725894-7066td8ghr1p1kgvm45no2ie22bpq8m7.apps.googleusercontent.com',
    iosBundleId: 'com.example.cocherasNestleWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp_J1xa2DUeIFfni8-jEoCtR-wS-JeRiw',
    appId: '1:321100725894:ios:b01087e9c9ecea88235b07',
    messagingSenderId: '321100725894',
    projectId: 'cocherasnestle',
    storageBucket: 'cocherasnestle.firebasestorage.app',
    androidClientId: '321100725894-i3l5nua49f92i5e0lvtu7qiju01krv0t.apps.googleusercontent.com',
    iosClientId: '321100725894-7066td8ghr1p1kgvm45no2ie22bpq8m7.apps.googleusercontent.com',
    iosBundleId: 'com.example.cocherasNestleWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3GHUyVhui6BwQmhQlW535SeLzoAWyJJg',
    appId: '1:321100725894:web:96cc340e94bd3686235b07',
    messagingSenderId: '321100725894',
    projectId: 'cocherasnestle',
    authDomain: 'cocherasnestle.firebaseapp.com',
    storageBucket: 'cocherasnestle.firebasestorage.app',
    measurementId: 'G-3LVT5V505H',
  );
}
